blog/views/auth.py
from flask import Blueprint, current_app, render_template, request, redirect, url_for
from flask_login import LoginManager, current_user, login_user, logout_user, login_required
from sqlalchemy.exc import IntegrityError

from blog.forms.user import RegistrationForm, LoginForm
from blog.models import User
from blog.models.database import db


auth_app = Blueprint('auth_app', __name__)

login_manager = LoginManager()
login_manager.login_view = "auth_app.login"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).one_or_none()


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for("auth_app.login"))


@auth_app.route('/signup/', methods=['GET', 'POST'], endpoint='signup')
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    
    error = None
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template('auth/register.html', form=form)

        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template('auth/register.html', form=form)
    
        user = User(username=form.username.data,
                    first_name=form.first_name.data,
                    last_name = form.last_name.data,
                    email = form.email.data,
                    is_staff = False,)
        user.hash_password = form.password.data
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create user!")
            error = "Could not create user!"
        else:
            current_app.logger.info("Created user %s", user)
            login_user(user)
            return redirect(url_for("index"))
        
    return render_template("auth/register.html", form=form, error=error)



@auth_app.route('/login/', methods=['GET', 'POST'], endpoint='login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    
    error = None
    form = LoginForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one_or_none()
        if user and user.validate_password(form.password.data):
            login_user(user)
            return redirect(url_for('index'))
        else:
            error = 'invalid username or password'

        
    return render_template('auth/login.html', form=form, error=error)


@auth_app.route('/logout/', endpoint='logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))



__all__ = [
    "login_manager",
    "auth_app",
]

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap5.css')}}">
    <title>
        {% block title %}
            Base Page
        {% endblock %}
    </title>

  </head>
  <body>
    <div class="container">
            {# nav bar #}
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('index') }}">Blog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
              aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">

            {% for (endpoint, label) in [('users_app.list', 'Users'), ('authors_app.list', 'Authors'), ('articles_app.list', 'Articles')] %}
              <a href="{{ url_for(endpoint) }}" class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                {{ label }}
              </a>
            {% endfor %}
              
            {% if current_user.is_authenticated %}
              <a class="nav-link" href="{{ url_for('auth_app.logout') }}">Logout</a>
            {% else %}
              {% for (endpoint, label) in [('auth_app.login', 'Login'), ('auth_app.signup', 'Sign Up')] %}
                <a href="{{ url_for(endpoint) }}" class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                  {{label}}
                </a>
              {% endfor %}
            {% endif %}
              
            </div>
          </div>
        </div>
      </nav>

        {% block content %}
        <h1>Hello from Base!</h1>
        
        {% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/bootstrap5.js')}}"></script>
  </body>
</html>

blog/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index Page
{% endblock %}

{% block content %}

<div class="jumbtron text-center">
    <h1>
        Welcome To MyBlog,
        {% if current_user.is_authenticated %}
            {{ current_user.username }}
        {% else %}
            anon
        {% endif %}
        !
    </h1>
    <p class="lead"> This is a blog application built on the Python Flask Framework and users can upload articles.</p>
</div>

{% endblock%}