blog/models/article.py
from .database import db
from sqlalchemy import Column, DateTime, Integer, String, Text, ForeignKey, func
from sqlalchemy.orm import relationship
from datetime import datetime

from .article_tag import article_tag_association_table

class Article(db.Model):
    id = Column(Integer, primary_key=True, nullable=False)
    author_id = Column(Integer, ForeignKey('author.id'))
    title = Column(String(100), nullable=False) 
    text = Column(Text, nullable=False, default="", server_default="")
    dt_created = Column(DateTime, default=datetime.utcnow, server_default=func.now())
    dt_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    author = relationship('Author', back_populates='articles')
    tags = relationship('Tag', secondary=article_tag_association_table, back_populates='articles')

    def __str__(self) -> str:
        return self.title

blog/forms/articles.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, SubmitField, TextAreaField, SelectMultipleField


class CreateArticleForm(FlaskForm):
    title = StringField('Title', [validators.DataRequired()])
    text = TextAreaField('Text', [validators.DataRequired()])
    tags = SelectMultipleField('Tags', coerce=int)

    submit = SubmitField('Create')

blog/views/articles.py
from flask import Blueprint, redirect, render_template, request, url_for, current_app
from werkzeug.exceptions import NotFound
from flask_login import login_required, current_user
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import joinedload

from blog.models.author import Author
from blog.models.article import Article
from blog.forms.articles import CreateArticleForm
from blog.models.database import db
from blog.models.tag import Tag

articles_app = Blueprint('articles_app', __name__)


"""articles = [
    {'id': 0,
    'title': 'First article',
    'content': 'Compile Bootstrap with your own asset pipeline by downloading our source Sass, JavaScript, and documentation files. This option requires some additional tooling: Sass compiler for compiling Sass source files into CSS files Autoprefixer for CSS vendor prefixing Should you require our full set of build tools, they are included for developing Bootstrap and its docs, but they are likely unsuitable for your own purposes.',
    'author': 1},
    {'id': 1,
    'title': 'Second article',
    'content': 'Compile Bootstrap with your own asset pipeline by downloading our source Sass, JavaScript, and documentation files. This option requires some additional tooling: Sass compiler for compiling Sass source files into CSS files Autoprefixer for CSS vendor prefixing Should you require our full set of build tools, they are included for developing Bootstrap and its docs, but they are likely unsuitable for your own purposes.',
    'author': 1 },
    { 'id': 2,
    'title': 'Third article',
    'content': 'Compile Bootstrap with your own asset pipeline by downloading our source Sass, JavaScript, and documentation files. This option requires some additional tooling: Sass compiler for compiling Sass source files into CSS files Autoprefixer for CSS vendor prefixing Should you require our full set of build tools, they are included for developing Bootstrap and its docs, but they are likely unsuitable for your own purposes.',
    'author': 3}
    ]
"""
@articles_app.route('/', endpoint='list')
def articles_list():
    articles = Article.query.all()
    return render_template('articles/list.html', articles=articles)


@articles_app.route('/tag/<int:tag_id>/', endpoint='tag_articles')
def articles_to_tag(tag_id):
    error = None
    tag_object = Tag.query.filter_by(id=tag_id).options(
        joinedload(Tag.articles)
        ).one_or_none()
    if tag_object is None:
        error = f'There is no such tag with id {tag_id}'
    return render_template('articles/list_to_tag.html', tag_object=tag_object, error=error)


@articles_app.route('/<int:article_id>/', endpoint='details')
@login_required
def article_details(article_id):
    choosen_article=Article.query.filter_by(id=article_id).options(
        joinedload(Article.tags)
        ).one_or_none()
    if choosen_article is None:
        raise NotFound(f'The article #{article_id} does not exist!')
    return render_template('articles/details.html', article=choosen_article)


@articles_app.route('/create/', methods=['GET', 'POST'], endpoint='article_create')
@login_required
def article_create():
    error = None
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]

    if request.method == "POST" and form.validate_on_submit:
        _article = Article(title = form.title.data, text = form.text.data)
        db.session.add(_article)

        if current_user.author:
            _article.author = current_user.author
        else:
            author = Author(id_user=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author = author

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create a new article!")
            error = "Could not create a new article!"
        else:    
            return redirect(url_for('articles_app.details', article_id=_article.id))

    return render_template('articles/create.html', form = form, error=error)

blog/templates/articles/create.html
{% extends 'base.html' %}
{% from 'macro/formhelper.html' import render_field %}

{% block title %}
 Create Article
{% endblock %}

{% block content %}
    <h1>Create Article</h1>
    {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
    {% endif %}
    <form action="" method="POST">
        {{ form.csrf_token() }}

        {% for field in ['title', 'text', 'tags'] %}
            {{ render_field(form[field]) }}
        {% endfor %}
        <div>
            {{ form.submit(class="btn btn-primary btn-lg") }}
        </div>
    </form>

{% endblock %}

blog/templates/articles/details.html
{% extends 'base.html' %}

{% block title %}
    Article # {{ article.id + 1 }}
{% endblock %}

{% block content %}
    <div class="row">
        <h1>{{ article.title }}</h1>
    </div>
    <div class="row">
        <div class="col-md-12">{{ article.text }}</div>
    </div>

    <div class="row">
        <div class="col-6">
            <div><small class="text-muted">Author: {{ article.author.user.first_name }} {{ article.author.user.last_name }}</small></div>
            <div><small class="text-muted">Created at: {{ article.dt_created.strftime('%d-%m-%Y %H:%M:%S') }}</small></div>
            <div><small class="text-muted">Updated at: {{ article.dt_updated.strftime('%d-%m-%Y %H:%M:%S') }}</small></div>
        </div>
        {% if article.tags %}
        <div class="col-6">
            {% for tag in article.tags %}
                <a href="{{ url_for('articles_app.tag_articles', tag_id=tag.id) }}">
                    <span class="badge bg-primary">{{ tag.name }}</span>
                </a>
            {% endfor %}
        </div>
        {% endif %}
    </div>

{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}
    Articles List
{% endblock %}

{% block content %}

    <h1>Articles</h1>
    <div>
        <div class="row row-cols-1 row-cols-md-4 g-4">
            {% for article in articles %}
            <div class="col">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ article.author.user.first_name }} {{ article.author.user.last_name }}</h6>
                        <p class="card-text">{{ article.text | truncate(50) }}</p>
                        <a href="{{ url_for('articles_app.details', article_id=article.id) }}"
                           class="card-link">Read</a>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Created at: {{ article.dt_created.strftime('%d-%m-%Y %H:%M:%S') }}</small>
                    </div>
                </div>
            </div>
            {% endfor%}
        </div>
        <hr>
        <a class="btn btn-primary btn-lg" href="{{ url_for('articles_app.article_create') }}">Create New Article</a>
    </div>
    


{% endblock %}

blog/templates/articles/list_to_tag.html
{% extends 'base.html' %}

{% block title %}
    Tag Articles
{% endblock %}

{% block content %}
    {% if error %}
        <div class="alert alert-danger" role="alert">
    {{ error }}
        </div>
    {% endif %}



    <h1>Articles to tag: "{{ tag_object.name }}"</h1>
    <div>
        {% if tag_object.articles %}
        <div class="row row-cols-1 row-cols-md-4 g-4">
                {% for article in tag_object.articles %}
                    <div class="col">
                        <div class="card h-100">
                            <div class="card-body">
                                <h5 class="card-title">{{ article.title }}</h5>
                                <h6 class="card-subtitle mb-2 text-muted">{{ article.author.user.first_name }} {{ article.author.user.last_name }}</h6>
                                <p class="card-text">{{ article.text | truncate(50) }}</p>
                                <a href="{{ url_for('articles_app.details', article_id=article.id) }}"
                                class="card-link">Read</a>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Created at: {{ article.dt_created.strftime('%d-%m-%Y %H:%M:%S') }}</small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
        </div>
        {% else %}
            <div>
                <h3>There are no articles!</h3>
            </div>
        {% endif %}
        <hr>
        <a class="btn btn-primary btn-lg" href="{{ url_for('articles_app.article_create') }}">Create New Article</a>
    </div>

    


{% endblock %}